# Generated by Django 4.2.7 on 2023-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('CrDate', models.DateTimeField()),
                ('MdFate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Link', models.CharField(max_length=200)),
                ('LinkType', models.CharField(max_length=30)),
                ('Preview', models.ImageField(max_length=255, upload_to='')),
                ('CrDate', models.DateTimeField()),
                ('MdFate', models.DateTimeField()),
                ('Collection', models.ManyToManyField(to='mainapp.collection')),
            ],
        ),
    ]
