# Generated by Django 4.1 on 2023-12-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('CrDate', models.DateTimeField()),
                ('MdFate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Link', models.CharField(max_length=200)),
                ('LinkType', models.CharField(blank=True, choices=[('website', 'Website'), ('book', 'Book'), ('article', 'Article'), ('music', 'Music'), ('video', 'Video')], default='website', max_length=10, null=True)),
                ('Preview', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('CrDate', models.DateTimeField(auto_now_add=True)),
                ('MdDate', models.DateTimeField(auto_now=True, null=True)),
                ('Collection', models.ManyToManyField(to='mainapp.collection')),
            ],
        ),
    ]
