# Generated by Django 4.1 on 2023-12-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='Collection',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.collection'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='MdDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
