# Generated by Django 4.1 on 2023-12-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='LinkType',
            field=models.ForeignKey(default='website', on_delete=django.db.models.deletion.CASCADE, to='mainapp.typelink'),
        ),
    ]
