# Generated by Django 4.1 on 2023-12-08 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_bookmark_collection_alter_bookmark_mddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link_type', models.CharField(blank=True, choices=[('website', 'Website'), ('book', 'Book'), ('article', 'Article'), ('music', 'Music'), ('video', 'Video')], default='website', max_length=10, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='CrDate',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='MdFate',
        ),
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='BookMark',
        ),
        migrations.AddField(
            model_name='parseddata',
            name='collections',
            field=models.ManyToManyField(blank=True, to='mainapp.collection'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.link'),
        ),
    ]
