# Generated by Django 4.1 on 2023-12-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_typelink_alter_bookmark_linktype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='MdFate',
            new_name='MdDate',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='CrDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='LinkType',
            field=models.ForeignKey(blank=True, default='website', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.typelink'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='Preview',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='Title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
