# Generated by Django 4.1 on 2023-12-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_mdfate_bookmark_mddate_alter_bookmark_crdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='LinkType',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('book', 'Book'), ('article', 'Article'), ('music', 'Music'), ('video', 'Video')], default='website', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='TypeLink',
        ),
    ]
