# Generated by Django 4.1 on 2023-12-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_bookmark_linktype_delete_typelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='MdDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
