# Generated by Django 4.1 on 2023-12-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_bookmark_mddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='MdDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
